language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
    - "8.4.0"
script:
  - "yarn jest"
after_success:
  - npm run travis-deploy-once "npm run semantic-release --dry-run"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
